[workspace]
resolver = "2"

members = [
    "modules/axalloc",
    "modules/axconfig",
    "modules/axdisplay",
    "modules/axdriver",
    "modules/axfs-ng",
    "modules/axhal",
    "modules/axlog",
    "modules/axmm",
    "modules/axdma",
    "modules/axnet",
    "modules/axns",
    "modules/axruntime",
    "modules/axsync",
    "modules/axtask",

    "api/axfeat",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Yuekai Jia <equation618@gmail.com>"]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
documentation = "https://arceos-org.github.io/arceos"
repository = "https://github.com/arceos-org/arceos"
keywords = ["arceos", "kernel"]
categories = ["os", "no-std"]

[workspace.dependencies]
axstd = { path = "ulib/axstd" }
axlibc = { path = "ulib/axlibc" }

arceos_api = { path = "api/arceos_api" }
arceos_posix_api = { path = "api/arceos_posix_api" }
axfeat = { path = "api/axfeat" }

axalloc = { path = "modules/axalloc" }
axconfig = { path = "modules/axconfig" }
axdisplay = { path = "modules/axdisplay" }
axdriver = { path = "modules/axdriver" }
axfs-ng = { path = "modules/axfs-ng" }
axhal = { path = "modules/axhal" }
axlog = { path = "modules/axlog" }
axmm = { path = "modules/axmm" }
axnet = { path = "modules/axnet" }
axns = { path = "modules/axns" }
axruntime = { path = "modules/axruntime" }
axsync = { path = "modules/axsync" }
axtask = { path = "modules/axtask" }
axdma = { path = "modules/axdma" }

allocator = { git = "https://github.com/arceos-org/allocator.git", tag = "v0.1.1" }
axcpu = "0.2"
axerrno = "0.1"
axfs-ng-vfs = { git = "https://github.com/Starry-Mix-THU/axfs-ng-vfs", rev = "0247038" }
axio = "0.1.1"
axplat = "0.1"
bindgen = "0.72"
cfg-if = "1.0"
chrono = { version = "0.4", default-features = false }
crate_interface = "0.1.4"
ctor_bare = "0.2"
kernel_guard = "0.1"
kspin = "0.1"
lazyinit = "0.2"
lock_api = { version = "0.4", default-features = false }
log = "=0.4.21"
memory_addr = "0.4"
memory_set = "0.4"
page_table_entry = "0.5"
page_table_multiarch = "0.5"
percpu = "0.2"
rand = "0.9"
spin = "0.9"

[profile.release]
lto = true

[patch.crates-io]
axcpu = { git = "https://github.com/Starry-Mix-THU/axcpu.git", rev = "b00d5a5" }
page_table_entry = { git = "https://github.com/Starry-Mix-THU/page_table_multiarch.git", rev = "e76ba3c" }
page_table_multiarch = { git = "https://github.com/Starry-Mix-THU/page_table_multiarch.git", rev = "e76ba3c" }
