[package]
name = "axdisplay"
version.workspace = true
edition.workspace = true
authors = ["Shiping Yuan <robert_yuan@pku.edu.com>"]
description = "ArceOS graphics module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axdisplay"
documentation = "https://arceos-org.github.io/arceos/axdisplay/index.html"

[dependencies]
axdriver = { workspace = true, features = ["display"] }
axsync = { workspace = true }

axdriver_display = { git = "https://github.com/Starry-Mix-THU/axdriver_crates.git", rev = "6168df5" }
lazyinit = { workspace = true }
log = { workspace = true }
