[package]
name = "axdisplay"
version.workspace = true
edition.workspace = true
authors = ["Shiping Yuan <robert_yuan@pku.edu.com>"]
description = "ArceOS graphics module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axdisplay"
documentation = "https://arceos-org.github.io/arceos/axdisplay/index.html"

[dependencies]
axdriver = { workspace = true, features = ["display"] }
axdriver_display.workspace = true
axsync.workspace = true
lazyinit.workspace = true
log.workspace = true
