[package]
name = "axlog"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Macros for multi-level formatted logging used by ArceOS"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axlog"
documentation = "https://arceos-org.github.io/arceos/axlog/index.html"

[features]
std = ["dep:chrono"]
log-level-off = ["log/max_level_off"]
log-level-error = ["log/max_level_error"]
log-level-warn = ["log/max_level_warn"]
log-level-info = ["log/max_level_info"]
log-level-debug = ["log/max_level_debug"]
log-level-trace = ["log/max_level_trace"]
default = []

[dependencies]
cfg-if.workspace = true
chrono = { workspace = true, default-features = true, optional = true }
crate_interface.workspace = true
kspin.workspace = true
log.workspace = true

[dev-dependencies]
axlog = { workspace = true, features = ["std"] }
